### ISSUE TITLE
Are PDS supported?

### ISSUE THREAD

**Issue by mike-cuche** [thilobillerbeck/skymoth#28]
Hello!
I'm trying to use Skymoth to crosspost from my Akkoma instance to my self-hosted PDS Server.
I entered my bluesky credentials and they got accepted (even there is no place to set a custom server), but no posts are being crossposted

**Comment by thilobillerbeck** [comment]
Hm, from what I understand when reading the docs this should work out of the box. But I'll try to test this myself and see if I encounter any bugs or problems so PDS can be supported.

**Comment by Otterface** [comment]
I've also tried using this with my own PDS, and initially it accepted my credentials (or appeared to) but after reloading the page it went back to saying I was unauthenticated with BlueSky and then when using the same credentials again I'm told they're invalid.

**Comment by thilobillerbeck** [comment]
I'm working on it :+1: 

https://github.com/thilobillerbeck/skymoth/commit/2b7e097797b3f81ce22c2015f254c7841d032365

**Comment by thilobillerbeck** [comment]
@Otterface @mike-cuche just published this feature, feel free to leave some feedback :)

**Comment by Otterface** [comment]
Logged in fine this morning and it immediately started bringing posts across, so I count that as a success!

I'll keep an eye on it over the week and make sure it sticks.

**Comment by thilobillerbeck** [comment]
since there were not complaints yet I'll close this
