### ISSUE TITLE
Posts show up in 'replies' tab on my Bluesky profile, not 'posts' tab

### ISSUE THREAD

**Issue by benjamineskola** [thilobillerbeck/skymoth#32]
**Describe the bug**
Posts that have been made to Bluesky via Skymoth don't appear in the Posts tab on my profile, but instead appear in the Replies tab.

I can't tell if this is intended behaviour (related to the 'Repost visibility control WIP' perhaps?) or if this is a bug.

**To Reproduce**
1. Make a post
2. It gets crossposted to bluesky, but shows up in the wrong tab

Something that _might_ be relevant is that every post I've made so far has been too long for bluesky, so it gets split into a thread by skymoth — does this cause the post to show up in Replies instead? It's not what I expect but of course not Skymoth's fault in that case.

edit: this seems like it might actually be the case, as a post that wasn't split shows up in the posts tab as expected.

**Expected behavior**
Posts show up in the posts tab; only replies show in the replies tab.

**Comment by benjamineskola** [comment]
This seems to work now 🤷🏻 either it's a bluesky fault or my expectations of how bluesky should behave are wrong, not a skymoth issue.

**Comment by xurizaemon** [comment]
Immediately after the toot was relayed, I also saw it show up in the "replies" tab only, and recalled seeing this issue in the queue. A couple of minutes later, I see it on my regular profile tab. So perhaps it's just delayed, at times?

**Comment by benjamineskola** [comment]
@xurizaemon yes that seems to match what I found. My guess is that Bluesky (or maybe specifically Bluesky's UI) is more asynchronous than I had realised.
