### ISSUE TITLE
Feature Request: Content Warning / Subject handling for text posts

### ISSUE THREAD

**Issue by Otterface** [thilobillerbeck/skymoth#40]
I noticed that with text posts that were originally under a content warning on Mastodon, they're cross posted with no evidence of such.

This was probably intended as Bluesky doesn't have custom content warning fields for posts.

Perhaps as a toggle option SkyMoth could append the CW field to the post with a prefix like "CW:"

**Comment by Baralheia** [comment]
I would like to see this as well - even if bsky doesn't directly support content warning/subject tags, it'd be awesome to have the option for SkyMoth to prepend the CW tag to posts.

Something like:
[CW: Content Warning Text]

**Comment by thilobillerbeck** [comment]
closed by https://github.com/thilobillerbeck/skymoth/releases/tag/v0.3.0
