### ISSUE TITLE
URLs posted incorrectly

### ISSUE THREAD

**Issue by RoseTheFlower** [thilobillerbeck/skymoth#49]
Including a URL in a Mastodon post (e.g. via the official web interface) results in it being posted as url [url] on Bluesky.

**Comment by xurizaemon** [comment]
Reproductions, in case it's helpful:

- https://toot.cafe/@xurizaemon/113618641062244361
- https://bsky.app/profile/did:plc:g2ymnk7l2xshxrf5wi5wbswm/post/3lcsu2d22zp2i

`every "popular library" on https://www.npmjs.com/ is a 404 if clicked` becomes `every "popular library" on [npmjs.com/](https://npmjs.com/) [https://www.npmjs.com/] is a 404 if clicked`

**Comment by thilobillerbeck** [comment]
fixed by c482266fd343e80669febe6175092c8a48ee86d5
