### ISSUE TITLE
Feature: User control of which Mastodon posts are relayed to BlueSky

### ISSUE THREAD

**Issue by xurizaemon** [thilobillerbeck/skymoth#55]
This is _Control which toots get reposted (currently only public "root" toots are reposted)_ from [Things to do](https://github.com/thilobillerbeck/skymoth?tab=readme-ov-file#things-to-do) in the project README.

### Existing constraints
- Recency - toots are only considered if they are in the users 50 most recent posts
- Check frequency - Skymoth checks each 60s by default (configured with `POLL_INTERVAL`)
- Is public - Skymoth only relays public toots
- Is not a mention - Skymoth only relays toots that don't start with `@`

https://github.com/thilobillerbeck/skymoth/blob/db8fae4362d62007a634919a8e905ae920254db4/lib/mastodon.ts#L35-L40

### Possible user controls
- Toot contains an allow-listed hashtag (eg #xp for "crosspost" in some tools)
- Toot does not contain a deny-listed hashtag (eg #noxp for "no crosspost" in some tools)
- Toot has been favourited by the posting user
- Toot contains media
- ...?

### Notes
- This configuration should be stored per-account, details of storage TBC
- Requires a value for "relay control" (eg: "all", "self-faved", "contains-marker") and a second value for any required marker text

**Comment by xurizaemon** [comment]
I want this feature myself! It's great to have a relay but I'd prefer a little more control, even though the defaults are working great so far.

To me, the ideal UX for this places control in the hands of the user at time of posting the original post. That means there's a UX in SkyMoth which configures the behaviour per relayed account, and some user action when posting to Mastodon/the source service which can be used to determine behaviour.

Options I've seen in other relay tools: 

1. Relay only posts that contain an allow list hashtag (eg #xp, #moa) or content (optionally removing the marker)
2. Relay posts unless they contain a deny list marker (eg #norelay)
3. Relay posts that are "favourited" by the posting user ⭐ ❤️ 

My preferred solution is the third - to me it has the lowest "noise" factor to folks on both Mastodon and BlueSky, and has the tidiest UX (post, hit fave). Some folks will find it weird to like their own posts, I know.

**Comment by xurizaemon** [comment]
Here's a mockup of some UI. Current UX is really straightforward (SPA, mostly single-URL), to me it seems we can put this configuration right by the user creds and it works.

https://github.com/user-attachments/assets/93ddfc37-6930-44ad-940e-ba01c8f30c2c

**Comment by xurizaemon** [comment]
A note on ⭐ -to-relay behaviour and timing 😄 

When relaying is conditional on the contents of the source post (as with "all" and "marker" options), the contents is populated immediately; any scheduled execution of the relay query will find the toot in the expected state.

When relaying is conditional on a property of the source post such as a ⭐ fave and the fave is added _after_ the post is created, then the scheduled execution may see the post without the fave applied.

Setting `POLL_INTERVAL` can reduce the chances of this being hit. We may also be able to apply this in the query (as "get most recent 50 faved posts" query will exclude non-faved posts, and pick them up on subsequent calls).

**Comment by xurizaemon** [comment]
Via #57 this is now implemented, so I will close this as fixed. Thanks @thilobillerbeck!

**Comment by thilobillerbeck** [comment]
sorry for the unnecessary ping :/
