### ISSUE TITLE
Images posting oddly without dimensions

### ISSUE THREAD

**Issue by alien-sunset** [thilobillerbeck/skymoth#74]
A recent (ish) Bsky update seems to be affecting skymoth masto -> bsky posts with images as I’ve noticed some oddness in the way images are being displayed 

https://github.com/bluesky-social/social-app/pull/6474

Likely just need to figure out some way to read the image dimensions and include those in the bsky post info

**Comment by thilobillerbeck** [comment]
fixed by fd16c289e0c25f5b3cfb82aab7c653c400321a07
